from .nine_gmm import NineGaussianMixture
from .twenty_five_gmm import TwentyFiveGaussianMixture
from .hard_funnel import HardFunnel
from .easy_funnel import EasyFunnel
from .many_well import ManyWell
from .control2d import Control2D
from .five_gmm import FiveGaussianMixture
from .four_banana import FourBananaMixture
from .michalewicz import Michalewicz
from .rastrigin import Rastrigin
from .rosenbrock import Rosenbrock