# `half_cheetah` configuration

num_sim_steps: 50
teleportation_freq: 1000

popsize: 400
prop_cmaes: 0.5

num_slices_to_use_for_eval: 1 # todo
num_eval_points_to_use: 100_000

bad_init: False
do_plots: True

plot_freq: 1 # plot every n steps
