# `half_cheetah` configuration

num_sim_steps: 1000 #2000
teleportation_freq: 10000

popsize: 10000
prop_cmaes: 0.5

num_slices_to_use_for_eval: 1 # todo
num_eval_points_to_use: 100_000

bad_init: True
do_plots: True

plot_freq: 999 # plot every n steps
